WIP: renames hypertrace-federated-service to hypertrace
hypertrace/hypertrace pull request #49
Opened 2020-09-09 00:01 UTC by adriancole

This simplifies the terminology we use by getting rid of the term "federated". It also makes image discovery easier by calling the top level docker image "hypertrace"

This is WIP as it requires a publish to fix the helm side accordingly

depends on https://github.com/hypertrace/hypertrace-service/pull/25
see https://github.com/hypertrace/hypertrace-service/issues/18

2020-09-09 08:58 UTC, jcchavezs commented
You better rebase.

2020-09-10 01:16 UTC, adriancole commented
There's a strange build break on hypertrace here https://github.com/hypertrace/hypertrace-service/issues/26 but I think we need dockerhub repo setup before publishing would work anyway https://github.com/hypertrace/hypertrace-service/issues/27

Until then, nothing to do here

2020-09-14 13:16 UTC, JBAhire submitted a review, later dismissed

2020-09-15 16:37 UTC, kotharironak requested changes
With this, we are observing CI pipeline failure. Let me have a look and will merge this.

2020-09-16 11:34 UTC, JBAhire submitted a review, later dismissed

2020-09-16 12:19 UTC, JBAhire approved these changes

2020-09-16 13:16 UTC, kotharironak approved these changes

2020-09-16 13:16 UTC, merged